# Generated by Django 3.2.5 on 2021-07-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='note',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
