# Generated by Django 3.2.5 on 2021-09-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='expiration_date',
            field=models.DateTimeField(default=None),
        ),
    ]
