# Generated by Django 3.2.5 on 2021-09-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_alter_note_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='expires',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='expiration_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
