# Generated by Django 3.2.5 on 2021-09-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20210904_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
    ]
