# Generated by Django 3.2.5 on 2021-09-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_alter_note_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
