# Generated by Django 3.2.5 on 2021-09-05 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_alter_note_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2021, 9, 5)),
        ),
    ]
