# Generated by Django 3.2.5 on 2021-09-05 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_alter_note_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
